# https://wiki.hyprland.org/Configuring/Monitors/
# use `hyprctl monitors` to get the info.

# Monitors
monitor=HDMI-A-1,preferred,0x0,auto
monitor=HDMI-A-2,preferred,2560x0,auto
monitor=DP-3,preferred,-1920x0,auto

# Some examples
#monitor = eDP-1, preferred, auto, 1
#monitor = eDP-1, 2560x1440@165, 0x0, 1 #own screen
#monitor = DP-3, 1920x1080@240, auto, 1 
#monitor = DP-1, preferred, auto, 1
#monitor = HDMI-A-1, preferred,auto,1

# High Refresh Rate
#monitor=,highrr,auto,1

# High Resolution
#monitor=,highres,auto,1

# to disable a monitor
#monitor=name,disable

# workspaces - Monitor rules
# https://wiki.hyprland.org/Configuring/Workspace-Rules/
# SUPER E - Workspace-Rules 
# See ~/.config/hypr/UserConfigs/WorkspaceRules.conf

